name: Website CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/**'
  push:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        typescript-version: [4.0.0]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Build
        run: cd website; yarn build
      - name: Lint
        run: cd website; yarn lint
      - name: Test
        run: cd website; yarn test

  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Build
        run: cd website; yarn build
      - name: Lint
        run: cd website; yarn lint
      - name: Test
        run: cd website; yarn test

  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        typescript-version: ['~4.0.0', '~4.1.0', latest]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run: |
          cd website
          yarn add typescript@${{ matrix.typescript-version}}
      - name: Build
        run: |
          cd website
          yarn build
      - name: TypeScript compile
        run: |
          cd website
          yarn replace-in-file 'import chalk' 'import * as chalk' node_modules/gatsby-cli/lib/reporter/reporter.d.ts
          yarn tsc
      - name: Lint
        run: |
          cd website
          yarn lint
      - name: Test
        run: |
          cd website
          yarn test
  publish:
    needs: [build, node-compatibility, ts-compatibility]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          working-dir: website
