name: Website

on:
  pull_request:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches: [main]
    paths:
      - 'website/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Build
        run: |
          cd website
          yarn build
      - name: Lint
        run: |
          cd website
          yarn lint
      - name: Test
        run: |
          cd website
          yarn test

  os-compatibility:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Build
        run: |
          cd website
          yarn build
      - name: Test
        run: |
          cd website
          yarn test

  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Build
        run: |
          cd website
          yarn build
      - name: Test
        run: |
          cd website
          yarn test

  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        typescript-version: ['~4.0.0', '~4.1.0', latest, next, beta, rc]
        include:
          - typescript-version: '~4.0.0'
            experimental: false
            name: 'ts-4.0'
          - typescript-version: '~4.1.0'
            experimental: false
            name: 'ts-4.1'
          - typescript-version: '~4.2.0'
            experimental: false
            name: 'ts-4.2'
          - typescript-version: latest
            experimental: false
            name: 'ts-stable'
          - typescript-version: beta
            experimental: false
            name: 'ts-beta'
          - typescript-version: rc
            experimental: true
            name: 'ts-rc'
          - typescript-version: next
            experimental: true
            name: 'ts-canary'


    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run: |
          cd website
          yarn add typescript@${{ matrix.typescript-version}}
      - name: Build
        run: |
          cd website
          yarn build
      - name: TypeScript compile
        run: |
          yarn replace-in-file 'import chalk' 'import * as chalk' node_modules/gatsby-cli/lib/reporter/reporter.d.ts
          cd website
          yarn tsc
      - name: Lint
        run: |
          cd website
          yarn lint
      - name: Test
        run: |
          cd website
          yarn test
  publish:
    needs: [build, os-compatibility, node-compatibility, ts-compatibility]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          working-dir: website
